yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата создания комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Коментарии'
        verbose_name = 'Коментарий'

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django.contrib.auth import get_user_model
from django import forms

from .models import Post, Comment


User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from datetime import datetime

from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.conf import settings
from django.views.decorators.cache import cache_page

from .models import Post, Group, User
from .forms import PostForm, CommentForm


@cache_page(20)
def index(request: HttpRequest) -> HttpResponse:
    """Функция для главной страницы.
    """
    template = 'posts/index.html'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = 'Последние обновления на сайте'
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


def group_posts(request: HttpRequest, slug: str) -> HttpResponse:
    """Функция для записей сообщества.
    """
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    paginator = Paginator(posts, settings.PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = f'Записи сообщества {group}'
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    """Функция для профайла пользователя.
    """
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count_posts = author.posts.count()
    paginator = Paginator(posts, settings.PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    title = f'Профайл пользователя {author}'
    context = {
        'author': author,
        'posts': posts,
        'count_posts': count_posts,
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    """Функция для просмотра записи.
    """
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    group = post.group
    author = post.author
    count_posts = author.posts.count()
    comments = post.comments.all()
    form = CommentForm()
    title = f'Пост {post.text[:30]}'
    context = {
        'form': form,
        'comments': comments,
        'post': post,
        'group': group,
        'count_posts': count_posts,
        'title': title,
    }
    return render(request, template, context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    """Функция для публикации постов.
    """
    template = 'posts/create_post.html'
    title = 'Создание поста'
    if request.method != 'POST':
        form = PostForm()
        context = {
            'form': form,
            'title': title,
        }
        return render(request, template, context)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        context = {
            'form': form,
            'title': title,
        }
        return render(request, template, context)
    post = form.save(commit=False)
    post.author = request.user
    post.pub_date = datetime.now()
    post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    """Функция для редактирования постов.
    """
    template = 'posts/update_post.html'
    post = get_object_or_404(Post, id=post_id, author=request.user)
    title = f'Редактрирование поста {post.id}'
    form = PostForm(instance=post)
    if request.method != 'POST':
        context = {
            'form': form,
            'is_edit': True,
            'post': post,
            'title': title,
        }
        return render(request, template, context)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': True,
            'title': title,
        }
        return render(request, template, context)
    post = form.save(commit=False)
    post.author = request.user
    post.pub_date = datetime.now()
    post.save()
    return redirect('posts:post_detail', post.id)


@login_required
def add_comment(request: HttpRequest,
                post_id: int) -> HttpResponse:
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post.id)

yatube/templates/posts/comments.html
{% load user_filters %}
{% if comments.count != 0 %}
  {% with comments.count as total_comments %}
  <hr>
  <figure>
    <blockquote class="blockquote">
      <div>
        Всего комментариев: {{ total_comments }}
      </div>
    </blockquote>
  </figure>
  {% endwith %}
{% else %}
  <hr>
  <figure>
    <blockquote class="blockquote">
      <div>
        Комментариев нет.
      </div>
    </blockquote>
  </figure>
{% endif %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="shadow-sm p-2 bg-light rounded">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Новый пост
          </div>
          <div class="card-body">        
            <form method="post" action =' ' enctype="multipart/form-data""
              {% if is_edit %}
                {% url 'posts:post_edit' post_id=post.id %}
              {% else %}
                {% url 'posts:post_create' %}
              {% endif %}
              ">
              {% csrf_token %}            
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста                  
                  <span class="required text-danger" >*</span>                  
                </label>
                {{ form.text }}           
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>                  
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Изображение                 
                </label>
                {{ form.image }}
                <small id="id_text-help" class="form-text text-muted">
                  Выберите изображение
                </small>
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа                 
                </label>
                <select name="group" class="form-control" id="id_group">
                  {% for group in form.group %}
                    {{ group }}
                  {% endfor %}
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Сохранить
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    <hr>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author %}">
              {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}</a><br>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}      
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-secondary">подробная информация</a>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}           
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    <h2>Последние обновления на сайте</h2>
    <hr>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author %}">
              {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}</a><br>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
          <li>
            Группа: {{ post.group.title }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-secondary">подробная информация</a>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-secondary">все записи группы</a>
        {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    <h2>Пост {{ post.text|truncatechars:30 }}</h2>
    <hr>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
          {% if post.group %}
          <li class="list-group-item">
            Группа: {{ group.title }}<br>
          </li>
          <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-light">все записи группы</a>
          {% endif %}
          <li class="list-group-item">
            Автор: <a href="{% url 'posts:profile' post.author %}">
              {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}</a><br>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span >{{ count_posts }}</span>
          </li>
            <a href="{% url 'posts:profile' post.author.username %}" class="btn btn-light">все посты пользователя</a>
            {% if user == post.author %}
            <a href="{% url 'posts:post_edit' post.id %}" class="btn btn-primary">Редактировать</a>
            {% endif %}
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
      </article>
      {% include "posts/comments.html" with comments=comments %}
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
  <div class="container py-5">
    <h2>Все посты пользователя {{ author.get_full_name }}</h2>
    <h3>Всего постов: {{ count_posts }}</h3>
    <hr>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: <a href="{% url 'posts:profile' post.author %}">
              {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}</a><br>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
          <li>
            Группа: {{ post.group.title }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}  
    </article>
      {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/update_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Редактировать пост {{ post.id }}
          </div>
          <div class="card-body">        
            <form method="post" action =' ' enctype="multipart/form-data""
              {% if is_edit %}
                {% url 'posts:post_edit' post_id=post.id %}
              {% else %}
                {% url 'posts:post_create' %}
              {% endif %}
              ">
              {% csrf_token %}            
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста                  
                  <span class="required text-danger" >*</span>                  
                </label>
                {{ form.text }}           
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>                  
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Изображение                 
                </label>
                {{ form.image }}
                <small id="id_text-help" class="form-text text-muted">
                  Выберите изображение
                </small>
              </div>           
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа                 
                </label>
                <select name="group" class="form-control" id="id_group">
                  {% for group in form.group %}
                    {{ group }}
                  {% endfor %}
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                </button> 
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}